apiVersion: v1
kind: Service
metadata:
  name: finacplus-blue-service
spec:
  type: LoadBalancer
  selector:
    app: finacplus
    version: blue
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30080

