apiVersion: v1
kind: Service
metadata:
  name: finacplus-service
spec:
  type: LoadBalancer
  selector:
    app: finacplus
    version: green
  ports:
    - port: 80
      targetPort: 9090
      nodePort: null
  type: NodePort

