apiVersion: v1
kind: Service
metadata:
  name: finacplus-service
spec:
  type: NodePort
  selector:
    app: finacplus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 31278


