apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finacplus-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: finacplus.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: finacplus-service
            port:
              number: 80

