apiVersion: apps/v1
kind: Deployment
metadata:
  name: finacplus-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finacplus
      version: blue
  template:
    metadata:
      labels:
        app: finacplus
        version: blue
    spec:
      containers:
      - name: finacplus
        image: /srinivas202/finacplus-bluegreen-app:latest
        env:
        - name: VERSION
          value: "blue"
        ports:
        - containerPort: 9090

